project:
  type: website
  output-dir: ../_site/en

bibliography: ../references.bib
csl: ../apa.csl

format:
  html:
    theme:
      - cosmo
      - ../synesis.scss
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: true
    highlight-style: github
    syntax-definitions:
      - ../synesis.xml

execute:
  freeze: auto

lang: en

website:
  title: "Synesis Language"
  navbar:
    title-href: "../../landing/"
    left:
      - href: index.qmd
        text: Introduction
      - text: "Tutorials"
        menu:
          - href: tutorials/guia_pesquisadores.qmd
            text: Guide for Researchers
          - href: tutorials/synesis_explorer_tutorial.qmd
            text: Synesis Explorer
      - text: "How-to Guides"
        menu:
          - href: howto/guia_profissionais.qmd
            text: Guide for Professionals
          - href: howto/exportar_neo4j.qmd
            text: Export to Neo4j
      - text: "Reference"
        menu:
          - href: reference/guia_referencia.qmd
            text: Language Reference
          - href: reference/synesis_load.qmd
            text: Synesis API
      - text: "Explanation"
        menu:
          - href: explanation/guia_sincero.qmd
            text: Why not Excel?
          - href: explanation/knowledge_graphs.qmd
            text: Knowledge Graphs & GraphRAG
          - href: explanation/ideas.qmd
            text: Roadmap & Ideas
      - href: about.qmd
        text: About
    right:
      - text: "ğŸŒ EN"
        menu:
          - text: "ğŸ‡§ğŸ‡· PortuguÃªs"
            href: ../pt/
          - text: "ğŸ‡¬ğŸ‡§ English"
            href: ../en/

  sidebar: false